name: build and deploy web api to azure

on:
    push:
        paths:
            - 'IaC/**'
        branches:
            - main
        
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              id: github
              uses: actions/checkout@v4

            - name: setup web api .net
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            